import sqlite3 as sql

import config

con = sql.connect(config.db)
con.execute("PRAGMA foreign_keys = ON")
cur = con.cursor()

cur.execute('''CREATE TABLE IF NOT EXISTS GUN(
SER TEXT PRIMARY KEY NOT NULL,
MOD TEXT
)''')

cur.execute('''CREATE TABLE IF NOT EXISTS BASE(
SER TEXT PRIMARY KEY NOT NULL,
MOD TEXT
)''')

cur.execute('''CREATE TABLE IF NOT EXISTS SHIPMENT(
ID INTEGER PRIMARY KEY NOT NULL,
GUN_SER TEXT,
BASE_SER TEXT,
CABLE INTEGER,
DATE TEXT,
TRACKING TEXT,
FOREIGN KEY (GUN_SER) REFERENCES GUN(SER),
FOREIGN KEY (BASE_SER) REFERENCES BASE(SER),
)''')

cur.execute('''CREATE TABLE IF NOT EXISTS INCIDENT(
INCIDENTNUM INTEGER PRIMARY KEY NOT NULL,
CALLDATE TEXT,
STORE_NUM TEXT,
STORE_CONTACT TEXT,
SENT_SHIPMENT_ID INT,
RECV_SHIPMENT_ID INT,
FOREIGN KEY (SENT_SHIPMENT_ID) REFERENCES SHIPMENT(ID),
FOREIGN KEY (RECV_SHIPMENT_ID) REFERENCES SHIPMENT(ID),
)''')

con.commit()










