import sqlite3 as sql

import config

con = sql.connect(config.db)
con.execute("PRAGMA foreign_keys = ON")
cur = con.cursor()

cur.execute('''CREATE TABLE IF NOT EXISTS GUN(
SER TEXT PRIMARY KEY NOT NULL,
MOD TEXT
)''')

cur.execute('''CREATE TABLE IF NOT EXISTS BASE(
SER TEXT PRIMARY KEY NOT NULL,
MOD TEXT
)''')

cur.execute('''CREATE TABLE IF NOT EXISTS INCIDENT(
INCIDENTNUM INTEGER PRIMARY KEY NOT NULL,
CALLDATE TEXT,
STORE_NUM TEXT,
STORE_CONTACT TEXT,
SENT_GUN TEXT,
SENT_BASE TEXT,
SENT_CABLE INTEGER,
SENT_SHIPDATE TEXT,
SENT_TRACKING TEXT, 
SENT_DELIVERDATE TEXT,
RECV_GUN TEXT,
RECV_BASE TEXT,
RECV_CABLE INTEGER,
RECV_DATE TEXT,
RECV_TRACKING TEXT,
FOREIGN KEY (SENT_GUN) REFERENCES GUN (SER),
FOREIGN KEY (SENT_BASE) REFERENCES BASE (SER),
FOREIGN KEY (RECV_GUN) REFERENCES GUN (SER),
FOREIGN KEY (RECV_BASE) REFERENCES BASE (SER)
)''')

con.commit()










