PRAGMA foreign_keys = ON;

CREATE TABLE GUN(
    SER TEXT PRIMARY KEY NOT NULL,
    MOD TEXT
);

CREATE TABLE BASE(
    SER TEXT PRIMARY KEY NOT NULL,
    MOD TEXT
);

CREATE TABLE INCIDENT(
    INCIDENTNUM INTEGER PRIMARY KEY NOT NULL,
    CALLDATE TEXT,
    STORE_NUM TEXT,
    STORE_CONTACT TEXT,
    SENT_GUN TEXT,
    FOREIGN KEY(SENT_GUN) REFERENCES GUN.(SER),
    SENT_BASE TEXT,
    FOREIGN KEY(SENT_BASE) REFERENCES BASE(SER),
    SENT_CABLE INTEGER,
    SENT_SHIPDATE TEXT,
    SENT_TRACKING TEXT, 
    SENT_DELIVERDATE TEXT,
    RECV_GUN TEXT,
    FOREIGN KEY(RECV_GUN) REFERENCES GUN(SER),
    RECV_BASE TEXT,
    FOREIGN KEY(RECV_BASE) REFERENCES BASE(SER),
    RECV_CABLE INTEGER,
    RECV_DATE TEXT,
    RECV_TRACKING TEXT
);