CREATE TABLE GUN(
SER TEXT PRIMARY KEY NOT NULL,
MOD TEXT
);

CREATE TABLE BASE(
SER TEXT PRIMARY KEY NOT NULL,
MOD TEXT
);

CREATE TABLE SHIPMENT(
ID INTEGER PRIMARY KEY NOT NULL,
GUN_SER TEXT,
BASE_SER TEXT,
CABLE INTEGER,
DATE TEXT,
TRACKING TEXT,
FOREIGN KEY (GUN_SER) REFERENCES GUN (SER),
FOREIGN KEY (BASE_SER) REFERENCES BASE (SER)
);

CREATE TABLE INCIDENT(
INCIDENTNUM INTEGER PRIMARY KEY NOT NULL,
CALLDATE TEXT,
STORE_NUM TEXT,
STORE_CONTACT TEXT,
SENT_SHIPMENT_ID INT,
RECV_SHIPMENT_ID INT,
FOREIGN KEY (SENT_SHIPMENT_ID) REFERENCES SHIPMENT (ID),
FOREIGN KEY (RECV_SHIPMENT_ID) REFERENCES SHIPMENT(ID)
);

CREATE TABLE USER(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME TEXT UNIQUE,
    HASH TEXT
);