CREATE TABLE GUN(
SER TEXT PRIMARY KEY NOT NULL,
MOD TEXT
);

CREATE TABLE BASE(
SER TEXT PRIMARY KEY NOT NULL,
MOD TEXT
);

CREATE TABLE SHIPMENT(
ID INTEGER PRIMARY KEY NOT NULL,
GUNSER TEXT,
BASESER TEXT,
CABLE INTEGER,
DATE TEXT,
TRACKING TEXT,
NOTES TEXT,
FOREIGN KEY (GUNSER) REFERENCES GUN (SER),
FOREIGN KEY (BASESER) REFERENCES BASE (SER)
);

CREATE TABLE INCIDENT(
INCIDENTNUM TEXT PRIMARY KEY NOT NULL,
CALLDATE TEXT,
STORENUM TEXT,
STORECONTACT TEXT,
SENT_SHIPMENT_ID INT,
RECV_SHIPMENT_ID INT,
NOTES TEXT,
FOREIGN KEY (SENT_SHIPMENT_ID) REFERENCES SHIPMENT (ID),
FOREIGN KEY (RECV_SHIPMENT_ID) REFERENCES SHIPMENT (ID)
);

CREATE TABLE USER(
ID INTEGER PRIMARY KEY NOT NULL,
NAME TEXT UNIQUE,
HASH TEXT
);