CREATE TABLE ITEM(
SERIALNUM TEXT PRIMARY KEY NOT NULL,
ITEMTYPE TEXT, 
MODELNUM TEXT
);

CREATE TABLE ITEMTRANSACTION(
ID INTEGER PRIMARY KEY NOT NULL,
SERIALNUM TEXT REFERENCES ITEM,
SHIPMENTID INTEGER REFERENCES SHIPMENT
);

CREATE TABLE SHIPMENT(
ID INTEGER PRIMARY KEY NOT NULL,
GUNSER TEXT,
BASESER TEXT,
CABLE INTEGER,
DATE TEXT,
TRACKING TEXT,
NOTES TEXT,
COMPLETED INTEGER,
DELIVEREDDATE TEXT,
DIRECTION INTEGER,
INCIDENTNUM TEXT REFERENCES INCIDENT
);

CREATE TABLE INCIDENT(
INCIDENTNUM TEXT PRIMARY KEY NOT NULL,
CALLDATE TEXT,
STORENUM TEXT,
STORECONTACT TEXT,
NOTES TEXT
);

CREATE TABLE USER(
ID INTEGER PRIMARY KEY NOT NULL,
NAME TEXT UNIQUE,
HASH TEXT
);